package View;

import static java.lang.String.valueOf;

import java.awt.Toolkit;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import Controlador.ClienteCadastroControlador;

public class ClienteView extends javax.swing.JFrame {
	
	private static final long serialVersionUID = 1L;

	private final ClienteCadastroControlador controlador;
	
   
    public ClienteView() {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(Login.class.getResource("/View/icones/car.png")));
    	setTitle("LavaJato - AutoBrilho");
        initComponents();
        this.controlador = new ClienteCadastroControlador(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setAlwaysOnTop(true);
        setResizable(false);
        setLocationRelativeTo(null); // Centralizar a janela na tela
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" CLIENTES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 50, 160, 60);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 63, 37, 16);

        tbCliente.setBackground(new java.awt.Color(153, 153, 153));
        tbCliente.setForeground(new java.awt.Color(255, 255, 255));
        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Nome", "CPF", "Endereço"
            }
        ));
        tbCliente.setGridColor(new java.awt.Color(0, 0, 0));
        tbCliente.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbCliente.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tbCliente);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 120, 1020, 440);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clientes");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 240, 107, 22);

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 51));
        btnCadastrar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar Novo Cliente");
        btnCadastrar.setBorder(null);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(140, 570, 220, 30);

        btnAlterar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnAlterar.setText("Alterar Cliente (Administrador)");
        btnAlterar.setBorder(null);
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(410, 570, 220, 30);
        btnAlterar.addActionListener(new ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnAlterarActionPerformed(evt);
        	}
        });

        btnRemover.setBackground(new java.awt.Color(204, 0, 0));
        btnRemover.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover.setText("Remover Cliente (Administrador)");
        btnRemover.setBorder(null);
        btnRemover.addActionListener(new ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnRemoverActionPerformed(evt);
        	}
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(680, 570, 220, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton2.setText("Retornar a Tela Principal");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(950, 570, 210, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/cadastro_cliente.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	System.out.println("Btn Alterar");
    }
    
    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	System.out.println("Btn Remover");
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	System.out.println("Btn Retornar");
    	this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	System.out.println("Cadastrar Novo Cliente");
    	controlador.novoCliente();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public boolean validarCampos(String nome, int cpf, int telefone, String endereco){
        if(nome.trim().isEmpty() || valueOf(cpf).isEmpty() || valueOf(telefone).isEmpty()|| endereco.trim().isEmpty()){
        	JOptionPane.showMessageDialog(this, "Campos não preenchidos!");
        	return false;
        }
        return true;   
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCliente;
    // End of variables declaration//GEN-END:variables

	public javax.swing.JTable getTbCliente() {
		return tbCliente;
	}

	public void setTbCliente(javax.swing.JTable tbCliente) {
		this.tbCliente = tbCliente;
	}

	private void iniciar() {
        this.controlador.atualizaTabela();
    }
}
