package View;
import java.awt.Color;

import javax.swing.JFrame;

import Controlador.ClienteCadastroControlador;
import Model.Cliente;
import Model.DAO.ClienteDAO;

public class NovoCliente extends javax.swing.JFrame {

	public NovoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();
        tbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setAlwaysOnTop(true);
        setResizable(false);
        setLocationRelativeTo(null); // Centralizar a janela na tela
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(860, 20, 190, 60);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereço");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 380, 120, 40);

        txtEndereco.setBackground(new java.awt.Color(204, 204, 204));
        txtEndereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEndereco.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(720, 380, 460, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(610, 290, 100, 40);

        txtTelefone.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(720, 290, 460, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 210, 90, 40);

        txtCpf.setBackground(new java.awt.Color(204, 204, 204));
        txtCpf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCpf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCpf);
        txtCpf.setBounds(720, 210, 460, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 120, 90, 40);

        txtNome.setBackground(new java.awt.Color(204, 204, 204));
        txtNome.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNome);
        txtNome.setBounds(720, 120, 460, 40);

        btnCadastrar.setBackground(new java.awt.Color(0, 153, 51));
        btnCadastrar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnCadastrar.setForeground(new Color(0, 0, 0));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(890, 470, 140, 40);

        btnRetornar.setBackground(new java.awt.Color(204, 204, 204));
        btnRetornar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnRetornar.setText("Retornar a Tela inicial");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetornar);
        btnRetornar.setBounds(960, 630, 220, 30);

        tbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/cadastro_cliente.jpg"))); // NOI18N
        getContentPane().add(tbackground);
        tbackground.setBounds(0, 0, 1590, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    	System.out.println("Btn Cadastrar");
    	
    	String nome = txtNome.getText();
    	String cpf = txtCpf.getText();
    	String telefone = txtTelefone.getText();
    	String endereco = txtEndereco.getText();
    	
    	Cliente modelo = new Cliente(0, nome, telefone, cpf, endereco);
    	
    	ClienteDAO dao = new ClienteDAO();
    	dao.insert(modelo);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
    	System.out.println("Btn Retornar");
    	this.dispose();
    }//GEN-LAST:event_btnRetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel tbackground;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
